create table aminoacids (
	image_name VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	three_letter_abv VARCHAR(3) NOT NULL,
    one_letter_abv VARCHAR(1) NOT NULL,
    category VARCHAR(50) NOT NULL,
    r_group VARCHAR(50) NOT NULL,
    isoelectric_point float NOT NULL,
    description VARCHAR(1028) NOT NULL,
    CONSTRAINT pk_three_letter_abv PRIMARY KEY (three_letter_abv)
);


create table aminoAcidCodons (
    codon_id SERIAL NOT NULL,
    three_letter_abv VARCHAR(50) NOT NULL,
    codon VARCHAR(50) NOT NULL,
    CONSTRAINT pk_codon_id PRIMARY KEY (codon_id)
);


create table nucleicAcids (
    image_name VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sugar VARCHAR(50) NOT NULL,
    description VARCHAR(1028) NOT NULL,
    CONSTRAINT pk_name PRIMARY KEY (name)
);

INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('glycine.jpg', 'Glycine', 'GLY', 'G', 'Nonpolar', 'Aliphatic', '5.97', 'Glycine is the smallest of the amino acids. It is ambivalent, meaning that it can be inside or outside of the protein molecule. In aqueous solution at or near neutral pH, glycine will exist predominantly as the zwitterion');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('alanine.jpg', 'Alanine', 'ALA', 'A', 'Nonpolar', 'Aliphatic', '6.00', 'Alanine is a hydrophobic molecule. It is ambivalent, meaning that it can be inside or outside of the protein molecule. The α carbon of alanine is optically active; in proteins, only the L-isomer is found. Alanine is the α-amino acid analog of the α-keto acid pyruvate, an intermediate in sugar metabolism. Alanine and pyruvate are interchangeable by a transamination reaction.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('proline.jpg', 'Proline', 'PRO', 'P', 'Nonpolar', 'Aliphatic', '6.30', 'Proline is formally NOT an amino acid, but an imino acid. Nonetheless, it is called an amino acid. The primary amine on the α carbon of glutamate semialdehyde forms a Schiff base with the aldehyde which is then reduced, yielding proline.Proline is often found at the end of α helix or in turns or loops. Unlike other amino acids which exist almost exclusively in the trans- form in polypeptides, proline can exist in the cis-configuration in peptides. The cis and trans forms are nearly isoenergetic. The cis/trans isomerization can play an important role in the folding of proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('valine.jpg', 'Valine', 'VAL', 'V', 'Nonpolar', 'Aliphatic', '5.96', 'Valine, an essential amino acid, is hydrophobic, and as expected, is usually found in the interior of proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('leucine.jpg', 'Leucine', 'LEU', 'L', 'Nonpolar', 'Aliphatic', '5.98', 'Leucine, an essential amino acid, is one of the three amino acid with a branched hydrocarbon side chain. It has one additional methylene group in its side chain compared with valine.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('isoleucine.jpg', 'Isoleucine', 'ILE', 'I', 'Nonpolar', 'Aliphatic', '6.02', 'Isoleucine, an essential amino acid, is one of the three amino acids having branched hydrocarbon side chains. It is usually interchangeable with leucine and occasionally with valine in proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('methionine.jpg', 'Methionine', 'MET', 'M', 'Nonpolar', 'Aliphatic', '5.74', 'Methionine, an essential amino acid, is one of the two sulfur-containing amino acids. The side chain is quite hydrophobic and methionine is usually found buried within proteins. Unlike cysteine, the sulfur of methionine is not highly nucleophilic, although it will react with some electrophilic centers. It is generally not a participant in the covalent chemistry that occurs in the active centers of enzymes.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('phenylalanine.jpg', 'Phenylalanine', 'PHE', 'F', 'Nonpolar', 'Aromatic', '5.48', 'As the name suggests, phenylalanine, an essential amino acid, is a derivative of alanine with a phenyl substituent on the β carbon. Phenylalanine is quite hydrophobic and even the free amino acid is not very soluble in water. Due to its hydrophobicity, phenylalanine is nearly always found buried within a protein. The π electrons of the phenyl ring can stack with other aromatic systems and often do within folded proteins, adding to the stability of the structure.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('tyrosine.jpg', 'Tyrosine', 'TYR', 'Y', 'Polar', 'aromatic', '5.66', 'Tyrosine, an essential amino acid, is also an aromatic amino acid and is derived from phenylalanine by hydroxylation in the para position. While tyrosine is hydrophobic, it is significantly more soluble that is phenylalanine. The phenolic hydroxyl of tyrosine is significantly more acidic than are the aliphatic hydroxyls of either serine or threonine, having a pKa of about 9.8 in polypeptides. As with all ionizable groups, the precise pKa will depend to a major degree upon the environment within the protein. Tyrosines that are on the surface of a protein will generally have a lower pKa than those that are buried within a protein; ionization yielding the phenolate anion would be exceedingly unstable in the hydrophobic interior of a protein.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('tryptophan.jpg', 'Tryptophan', 'TRP', 'W', 'Nonpolar', 'Aromatic', '5.89', 'Tryptophan, an essential amino acid, is the largest of the amino acids. It is also a derivative of alanine, having an indole substituent on the β carbon. The indole functional group absorbs strongly in the near ultraviolet part of the spectrum. The indole nitrogen can hydrogen bond donate, and as a result, tryptophan, or at least the nitrogen, is often in contact with solvent in folded proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('serine.jpg', 'Serine', 'SER', 'S', 'Polar', 'Uncharged', '5.58', 'Serine is one of two hydroxyl amino acids. Both are commonly considered to by hydrophilic due to the hydrogen bonding capacity of the hydroxyl group.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('threonine.jpg', 'Threonine', 'THR', 'T', 'Polar', 'Uncharged', '5.60', 'Threonine, an essential amino acid, is a hydrophilic molecule. Note that both the α and β carbons of threonine are optically active.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('cysteine.jpg', 'Cysteine', 'CYS', 'C', 'Polar', 'Uncharged', '5.07', 'Cysteine is one of two sulfur-containing amino acids; the other is methionine. Cysteine differs from serine in a single atom-- the sulfur of the thiol replaces the oxygen of the alcohol. The amino acids are, however, much more different in their physical and chemical properties than their similarity might suggest. Cysteine also plays a key role in stabilizing extracellular proteins. Cysteine can react with itself to form an oxidized dimer by formation of a disulfide bond. The environment within a cell is too strongly reducing for disulfides to form, but in the extracellular environment, disulfides can form and play a key role in stabilizing many such proteins, such as the digestive enzymes of the small intestine.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('asparagine.jpg', 'Asparagine', 'ASN', 'N', 'Polar', 'Uncharged', '5.41', 'Asparagine is the amide of aspartic acid. The amide group does not carry a formal charge under any biologically relevant pH conditions. The amide is rather easily hydrolyzed, converting asparagine to aspartic acid. This process is thought to be one of the factors related to the molecular basis of aging. Asparagine has a high propensity to hydrogen bond, since the amide group can accept two and donate two hydrogen bonds. It is found on the surface as well as buried within proteins. Asparagine is a common site for attachment of carbohydrates in glycoproteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('glutamine.jpg', 'Glutamine', 'GLN', 'Q', 'Polar', 'Uncharged', '5.65', 'Glutamine is the amide of glutamic acid, and is uncharged under all biological conditions.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('lysine.jpg', 'Lysine', 'LYS', 'K', 'Basic', 'Positively Charged', '9.74', 'Lysine. an essential amino acid, has a positively charged ε-amino group (a primary amine).The amino group is highly reactive and often participates in a reactions at the active centers of enzymes.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('arginine.jpg', 'Arginine', 'ARG', 'R', 'Basic', 'Positively Charged', '10.76', 'Arginine, an essential amino acid, has a positively charged guanidino group. Arginine is well designed to bind the phosphate anion, and is often found in the active centers of proteins that bind phosphorylated substrates. As a cation, arginine, as well as lysine, plays a role in maintaining the overall charge balance of a protein.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('histidine.jpg', 'Histidine', 'HIS', 'H', 'Basic', 'Positively Charged', '7.59', 'Histidine, an essential amino acid, has as a positively charged imidazole functional group. The imidazole makes it a common participant in enzyme catalyzed reactions. The unprotonated imidazole is nucleophilic and can serve as a general base, while the protonated form can serve as a general acid. The residue can also serve a role in stabilizing the folded structures of proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('aspartate.jpg', 'Aspartate', 'ASP', 'D', 'Acidic', 'Negatively Charged', '2.77', 'Aspartic acid is one of two acidic amino acids. Aspartic acid and glutamic acid play important roles as general acids in enzyme active centers, as well as in maintaining the solubility and ionic character of proteins.');
INSERT INTO aminoacids (image_name, name, three_letter_abv, one_letter_abv, category, r_group, isoelectric_point, description) VALUES ('glutamate.jpg', 'Glutamate', 'GLU', 'E', 'Acidic', 'Negatively Charged', '3.22', 'Glutamic acid has one additional methylene group in its side chain than does aspartic acid. The side chain carboxyl of aspartic acid is referred to as the β carboxyl group, while that of glutamic acid is referred to as the γ carboxyl group');

INSERT INTO nucleicAcids (image_name, name, category, sugar, description) VALUES ('Adenine.png', 'Adenine', 'Purine', 'DNA and RNA', 'Adenine is a purine base. Adenine is found in both DNA and RNA. Adenine is a fundamental component of adenine nucleotides. Adenine forms adenosine, a nucleoside, when attached to ribose, and deoxyadenosine when attached to deoxyribose; it forms adenosine triphosphate (ATP), a nucleotide, when three phosphate groups are added to adenosine.');
INSERT INTO nucleicAcids (image_name, name, category, sugar, description) VALUES ('Thymine.png', 'Thymine', 'Pyrimidine', 'DNA', 'Thymine is a pyrimidine nucleobase. As the name implies, thymine may be derived by methylation of uracil at the 5th carbon. Thymine is found in the nucleic acid DNA. In RNA thymine is replaced with uracil in most cases. In DNA, thymine binds to adenine via two hydrogen bonds to assist in stabilizing the nucleic acid structures.');
INSERT INTO nucleicAcids (image_name, name, category, sugar, description) VALUES ('Cytosine.png', 'Cytosine', 'Pyrimidine', 'DNA and RNA', 'Cytosine is a pyrimidine base that is a fundamental unit of nucleic acids. The deamination of cytosine alone is apparent and the nucleotide of cytosine is the prime mutagenic nucleotide in leukaemia and cancer. Cytosine pairs with Guanine using 3 hydrogen bonds');
INSERT INTO nucleicAcids (image_name, name, category, sugar, description) VALUES ('Guanine.png', 'Guanine', 'Purine', 'DNA and RNA', 'Guanine is one of the five main nucleobases found in the nucleic acids DNA and RNA. Guanine is a derivative of purine, consisting of a fused pyrimidine-imidazole ring system with conjugated double bonds. Guanine binds with Cytosine using 3 hydrogen bonds.');
INSERT INTO nucleicAcids (image_name, name, category, sugar, description) VALUES ('Uracil.png', 'Uracil', 'Pyrimidine', 'RNA', 'Uracil is a common naturally occurring pyrimidine found in RNA, it base pairs with adenine and is replaced by thymine in DNA. Methylation of uracil produces thymine. Its use in the body is to help carry out the synthesis of many enzymes necessary for cell function through bonding with riboses and phosphates.');



ALTER TABLE aminoAcidCodons ADD FOREIGN KEY (three_letter_abv) REFERENCES aminoacids(three_letter_abv);

